export const WORDLES = [
  'BUICK', 'CHEVY', 'MOTOR', 'OWNER', 'TEAMS', 'RETRO', 'BUILD', 'BRAND', 'OFFER', 'YUKON',
  'TRUCK', 'BLAZE', 'TRAIL', 'FLEET', 'SPARK', 'SCRUM', 'IMAGE', 'CYBER', 'DRIVE', 'TEXAS',
  'AZURE', 'CARLY', 'PLANT', 'STORE', 'LOGIC', 'SPEED', 'HUMAN', 'LEGAL', 'TRACK', 'ORDER',
  'SMART', 'EMAIL', 'EVENT', 'STAND', 'BLOCK', 'TODAY', 'THEME', 'BOARD', 'ERROR', 'LOGIN',
  'SHEET', 'DELAY', 'LOCAL', 'STORY', 'LYRIQ', 'MONTH', 'CLICK', 'APPLY', 'LOWER', 'TOKEN',
  'MERGE', 'TRUNK', 'VALUE', 'SUPER', 'LEARN', 'ADOBE', 'GROOM', 'THINK', 'ISSUE', 'PRICE',
  'REPLY', 'FINAL', 'MICRO', 'DAILY', 'BUDDY', 'AWARD', 'GLOBE', 'CRASH', 'CHIEF', 'PILOT'
]